Leaner image.
Reorganized files in repo to simplify or reduce Dockerfile ADD/COPY
commands.

Removed rclone.conf requirement since plex_autoscan doesn't explicitly
require rclone, only to refresh a mounted cache.

Targeted /config permissions restoration.

Inspired by doob187, added a healthcheck for the Plex config entries.

Inspired by qstore2, removed unnecessary build dependencies from image.

diff --git a/root/etc/cont-init.d/10-init_user_and_fix_permissions b/root/etc/cont-init.d/10-init_user_and_fix_permissions
--- a/root/etc/cont-init.d/10-init_user_and_fix_permissions
+++ b/root/etc/cont-init.d/10-init_user_and_fix_permissions
@@ -53,10 +53,14 @@ dockergroup=$(getent group $dockergid | awk -F: '{print $1}')
 if [ $dockergroup ] && [ $dockergroup == "docker" ]
 then
     debug_echo "Container's docker group's GID matches requested DOCKERGID $dockergid, no changes necessary: $(getent group $dockergid)"
+elif [ $dockergroup ] && [ $dockergroup != "docker"]
+then
+    echo "ERROR: an existing group uses the desired docker GID $dockergid, please select a new dockergid value."
+    exit 1
 else
-    debug_echo "Container's docker group's GID does not match requested DOCKERGID $dockergid, updating docker group."
-    groupmod -o -g $dockergid docker
-    debug_echo "docker group GID updated to $dockergid."
+    debug_echo "docker group does not exist, creating with GID $dockergid."
+    addgroup -g $dockergid -S docker
+    debug_echo "docker group create with GID $dockergid."
 fi
 
 user=$(getent passwd $uid | awk -F: '{print $1}')
@@ -85,9 +89,11 @@ else
         "
 fi
 
-chown -R $uid:$gid /config
-find /config -type d -exec chmod 0777 {} +
-chmod 0666 /config/config.json
+chown $uid:$gid /config
+chmod u+rwx /config
+cd /config
+chown $uid:$gid cache.db config.json* plex_autoscan.log* queue.db
+chmod u+rw cache.db config.json* plex_autoscan.log* queue.db
 
 chown -R $uid:$gid /opt/plex_autoscan
 find /opt/plex_autoscan -type d -exec chmod 0775 {} +
